# This is a basic workflow to help you get started with Actions

name: Build Game

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  buildLinux:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@main

      - uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.3.6

      # Runs a set of commands using the runners shell
      - name: Install libvlc
        run: sudo apt-get install -y libvlc-dev libvlccore-dev

      - name: Install Haxelib
        run: |
          haxelib setup C:/haxelib
          haxelib install lime 7.9.0
          haxelib install openfl 9.1.0
          haxelib install flixel 4.11.0
          haxelib install flixel-addons 2.11.0
          haxelib install flixel-ui 2.4.0
          haxelib install hscript 2.4.0
          haxelib git hscript-improved https://github.com/FNF-CNE-Devs/hscript-improved codename-dev
          haxelib git hxvlc https://github.com/MAJigsaw77/hxvlc
          haxelib git hxcpp https://github.com/HaxeFoundation/hxcpp
          haxelib git linc_luajit https://github.com/Leather128/linc_luajit.git
          haxelib git flxanimate https://github.com/Vortex2Oblivion/flxanimate
          haxelib git scriptless-polymod https://github.com/Vortex2Oblivion/scriptless-polymod
          haxelib git hxNoise https://github.com/whuop/hxNoise
          haxelib git discord_rpc https://github.com/Aidan63/linc_discord-rpc
          haxelib git fnf-modcharting-tools https://github.com/Vortex2Oblivion/FNF-Modcharting-Tools
          haxelib git funkin.vis https://github.com/FunkinCrew/funkVis
          haxelib git grig.audio https://gitlab.com/haxe-grig/grig.audio
      - name: Create Version Tag
        run: echo "${{github.run_id}}" > VERSION
      - name: Compile Linux
        run: |
          cd $(haxelib libpath hxcpp)/tools/hxcpp
          haxe compile.hxml
          cd -
          haxelib --always run lime build Project.xml linux --app-version="4.0.0-${{ github.run_id}}"
      - name: Publish Linux Artifact
        uses: actions/upload-artifact@main
        with:
          name: linuxBuild
          path: "export/release/linux/bin"

  buildWindows:
    runs-on: windows-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@main

      - uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.3.6
      
      # Runs a set of commands using the runners shell
      - name: Install Haxelib
        shell: cmd
        run: |
          haxelib setup ~/haxelib
          haxelib install lime 8.1.3
          haxelib install openfl 9.2.1
          haxelib install flixel 4.11.0
          haxelib install flixel-addons 2.11.0
          haxelib install flixel-ui 2.4.0
          haxelib install hscript 2.4.0
          haxelib git hscript-improved https://github.com/FNF-CNE-Devs/hscript-improved codename-dev
          haxelib git hxvlc https://github.com/MAJigsaw77/hxvlc
          haxelib git hxcpp https://github.com/HaxeFoundation/hxcpp
          haxelib git linc_luajit https://github.com/Leather128/linc_luajit.git
          haxelib git flxanimate https://github.com/Vortex2Oblivion/flxanimate
          haxelib git scriptless-polymod https://github.com/Vortex2Oblivion/scriptless-polymod
          haxelib git hxNoise https://github.com/whuop/hxNoise
          haxelib git discord_rpc https://github.com/Aidan63/linc_discord-rpc
          haxelib git fnf-modcharting-tools https://github.com/Vortex2Oblivion/FNF-Modcharting-Tools
          haxelib git funkin.vis https://github.com/FunkinCrew/funkVis
          haxelib git grig.audio https://gitlab.com/haxe-grig/grig.audio
          haxelib run lime setup -y
      - name: Create Version Tag
        run: echo "${{github.run_id}}" > VERSION
      - name: Compile
        shell: bash
        run: |
          haxelib run lime setup -y
          haxelib run lime build windows -release -D no-compilation
      - name: Publish Artifact
        uses: actions/upload-artifact@main
        with:
          name: windowsBuild
          path: export/release/windows/bin
      - name: Force Haxelib
        shell: bash
        run: |
          haxelib dev flixel /home/runner/haxelib/flixel/4,11,0
          haxelib dev openfl /home/runner/haxelib/openfl/9,2,1
          haxelib dev lime /home/runner/haxelib/lime/8,1,3

  buildMac:
    runs-on: macos-12

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@main

      - uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.3.6
      
      # Runs a set of commands using the runners shell
      - name: Install Haxelib
        run: |
          haxelib setup C:/haxelib
          haxelib install lime 7.9.0
          haxelib install openfl 9.1.0
          haxelib install flixel 4.11.0
          haxelib install flixel-addons 2.11.0
          haxelib install flixel-ui 2.4.0
          haxelib install hscript 2.4.0
          haxelib git hxcpp https://github.com/HaxeFoundation/hxcpp
          haxelib git linc_luajit https://github.com/Leather128/linc_luajit.git
          haxelib git flxanimate https://github.com/Vortex2Oblivion/flxanimate
          haxelib git scriptless-polymod https://github.com/Vortex2Oblivion/scriptless-polymod
          haxelib git hxNoise https://github.com/whuop/hxNoise
          haxelib git discord_rpc https://github.com/Aidan63/linc_discord-rpc
          haxelib git fnf-modcharting-tools https://github.com/Vortex2Oblivion/FNF-Modcharting-Tools
          haxelib git funkin.vis https://github.com/FunkinCrew/funkVis
          haxelib git grig.audio https://gitlab.com/haxe-grig/grig.audio
      - name: Create Version Tag
        run: echo "${{github.run_id}}" > VERSION
      - name: Compile
        run: |
          cd $(haxelib libpath hxcpp)/tools/hxcpp
          haxe compile.hxml
          cd -
          haxelib --always run lime build mac --app-version="4.0.0-${{ github.run_id}}"
      - name: Publish Artifact
        uses: actions/upload-artifact@main
        with:
          name: macBuild
          path: export/release/macos/bin
